### ISSUE TITLE
CHB-MIT (Physionet) error - regular EDF not supported anymore

### ISSUE THREAD

**Issue by zaccharieramzi** [Teuniz/EDFbrowser#33] opened 2017-06-12 13:13 UTC
Hi,

So I am having an issue opening some edf files from the [CHB-MIT database](https://physionet.nlm.nih.gov/pn6/chbmit/) in EDFbrowser. I happen to have signaled this issue for `pyedflib` and it was solved by @holgern in [this commit](https://github.com/holgern/pyedflib/commit/4bd9e547c62cb207f6d9e421807811bc076bb527).

I am not sufficiently proficient in C to be able to correct it again here, but I can try if no one is up to it. I think similarly, what should change is [here](https://github.com/Teuniz/EDFbrowser/blob/master/edflib.c#L2082), but then again I am not a proficient C coder.

I also refer another error that I am currently submitting in `pyedflib` since it probably has to do with and EDF/EDF+ mess again: https://github.com/holgern/pyedflib/issues/17 .

Don't hesitate to ask for additional details and thanks in advance for your help.

**Comment by Teuniz** [comment] 2017-06-12 16:34
Hello Zaccharieramzi,

Can you give me a link to an EDF file that doesn't open correctly in EDFbrowser.
I just downloaded the first EDF file from CHB-MIT database and it opens fine.

**Comment by zaccharieramzi** [comment] 2017-06-12 17:18
Yes, that is correct.

It's only after the 12th patient that this is not possible. I give some details on why it happens in [this issue](https://github.com/holgern/pyedflib/issues/14).

Also, like I said there appears to be another problem, at least in `pyedflib` that has nothing to do with digital minimas this time.

**Comment by Teuniz** [comment] 2017-06-12 17:32
I downloaded chb01_1.edf, chb01_13.edf and chb01_40.edf from https://physionet.nlm.nih.gov/pn6/chbmit/chb01/ and all three opened fine.
I can't help you if you don't point me to a file that demonstrates the problem.

**Comment by Teuniz** [comment] 2017-06-12 17:51
I found a file that demonstrated your problem: https://physionet.nlm.nih.gov/pn6/chbmit/chb16/chb16_16.edf
EDFbrowser refuses to open it and shows the following message:
"Error, digital maximum of signal 5 is less than or equal to digital minimum
 File is not a valid EDF or BDF file."

This is done by purpose to enforce file compatibility. In the EDF header, digital maximum should be higher than digital minimum. Despite it's not literally written in the EDF standard, it's my opinion
that signal inversion should be accomplished by manipulating the physical maximum and minimum values. Not the digital values. Hence the correction and advice written here:
http://edfplus.info/specs/edfplus.html#additionalspecs
"5. 'Digital maximum' must be larger than 'Digital minimum'. In case of a negative amplifier gain the corresponding 'Physical maximum' is smaller than the 'Physical minimum'."

I'm sorry but I can't help you with that. It's the responsability of the programmer that wrote the software that produced that file to fix it.
Let me know if there's something else I can do for you.

Kind Regards,

Teunis van Beelen

**Comment by zaccharieramzi** [comment] 2017-06-12 17:56
You are right, it's said in the specs, however it's only for EDF+ not regular EDF. To me the fact that it's explicitly written for EDF+ means that it's not the case for regular EDF.

The programmer who wrote the software did it intentionally for presentation purposes (it's said in the description of the database). Plus, I think it would be a shame if EDFbrowser couldn't open files from this database as it is largely used in scientific articles for work on epileptic seizures.

**Comment by Teuniz** [comment] 2017-06-19 18:37
I had a closer look at the file: https://physionet.nlm.nih.gov/pn6/chbmit/chb16/chb16_16.edf and
it appears that the problem is not that digital maximum is lower than digital minimum, but they are equal.
When both values for digital max and min are equal, it's impossible to calculate the sensitivity of the signal. Sensitivity (e.g. uV/bit) is calculated as follows: (physmax - physmin) / (digmax - digmin),
so, when digmax and digmin are equal, you'll get a divide by zero error and the program will crash.
Even if beeing checked for this kind of error, it makes no sense to put a signal into an EDF file that contains no data. The only good solution is to remove these empty signals from the file.

**Comment by zaccharieramzi** [comment] 2017-06-26 15:03
Yes, it's exactly that. A lot of files, starting from patient chb12, contain an "empty" channel. They are here intentionally as specified in the [presentation](https://physionet.nlm.nih.gov/pn6/chbmit/) of the CHB-MIT database:

> In some cases, up to 5 “dummy” signals (named "-") were interspersed among the EEG signals to obtain an easy-to-read display format; these dummy signals can be ignored.

Indeed, it would be a solution to just get rid of those signals but it's something to be avoided since it is a data that is provided as is for a lot of people (so it's not scalable).

I don't understand why there is a need to compute the sensitivity of the signal, and why it couldn't be possible for the cases where there is a zero-division error to set it as NaN.

**Comment by Teuniz** [comment] 2017-06-26 19:06
The problem has been solved. Next time, if you try to open a file and EDFbrowser shows an error message saying that "digital maximum of signal n is less than or equal to digital minimum.",
do as follows: In EDFbrowser go to Tools -> Header editor. Select the file. Now click on the
"save" button (you don't need to edit the content manually). Close the header editor.
Now open the file in the usual way.
If you are in a hurry and if you are using Linux, you can pull the source from Github and compile EDFbrowser in order to use this patch.

**Comment by zaccharieramzi** [comment] 2017-06-28 16:10
So this will modify the file?

**Comment by Teuniz** [comment] 2017-06-28 19:23
Yes, it will. It needs to be done only one time for each problematic file.

**Comment by Teuniz** [comment] 2017-09-16 14:47
Closed because the issue has been resolved with version 1.60 (released now).

**Closed by Teuniz** 2017-09-16 14:47 UTC
